In [2]:
import pandas as pd

df = pd.read_csv("./data_cleaning/Dataset_DataCleaning_Employee250.csv")
df

,Gender,Department,Experience_Years,Certifications,Salary,Satisfaction_Score,Age,Performance_Rating,Employment_Type
0,Male,Engineering,11.0,1,60671.81,9.49,32.0,2.0,Part-time
1,Male,Engineering,4.0,1,45659.33,3.97,NaN,3.1,Part-time
2,Male,Marketing,NaN,3,28771.96,9.54,24.0,2.4,NaN
3,Male,Marketing,3.0,1,NaN,1.35,38.0,3.1,Contract
4,Male,Engineering,5.0,3,18813.08,4.84,49.0,1.5,Full-time
...,...,...,...,...,...,...,...,...,...
245,Male,HR,5.0,0,46661.88,8.26,45.0,4.3,Contract
246,Male,Marketing,11.0,3,62366.23,2.98,55.0,2.3,Intern
247,Male,HR,20.0,2,NaN,8.40,46.0,1.1,NaN
248,Female,Marketing,7.0,1,61220.52,7.73,50.0,1.6,Contract
249,Male,Marketing,3.0,0,72514.57,2.30,52.0,1.9,Contract

In [3]:
df.head() #  display the first 5 rows of a DataFrame

,Gender,Department,Experience_Years,Certifications,Salary,Satisfaction_Score,Age,Performance_Rating,Employment_Type
0,Male,Engineering,11.0,1,60671.81,9.49,32.0,2.0,Part-time
1,Male,Engineering,4.0,1,45659.33,3.97,NaN,3.1,Part-time
2,Male,Marketing,NaN,3,28771.96,9.54,24.0,2.4,NaN
3,Male,Marketing,3.0,1,NaN,1.35,38.0,3.1,Contract
4,Male,Engineering,5.0,3,18813.08,4.84,49.0,1.5,Full-time

In [4]:
df.info() # summary of the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Gender              250 non-null    object
 1   Department          250 non-null    object
 2   Experience_Years    249 non-null    float64
 3   Certifications      250 non-null    int64
 4   Salary              224 non-null    float64
 5   Satisfaction_Score  250 non-null    float64
 6   Age                 224 non-null    float64
 7   Performance_Rating  225 non-null    float64
 8   Employment_Type     242 non-null    object
dtypes: float64(5), int64(1), object(3)
memory usage: 17.7+ KB

In [5]:
df.isna() #True for missing and False for non null values

,Gender,Department,Experience_Years,Certifications,Salary,Satisfaction_Score,Age,Performance_Rating,Employment_Type
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False
2,False,False,True,False,False,False,False,False,True
3,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
245,False,False,False,False,False,False,False,False,False
246,False,False,False,False,False,False,False,False,False
247,False,False,False,False,True,False,False,False,True
248,False,False,False,False,False,False,False,False,False
249,False,False,False,False,False,False,False,False,False

In [6]:
df.isna().sum() #count of null / missing values in each column

Gender                 0
Department             0
Experience_Years       1
Certifications         0
Salary                26
Satisfaction_Score     0
Age                   26
Performance_Rating    25
Employment_Type        8
dtype: int64

In [7]:
df.drop(['Gender'], axis=1) #drop the column

,Department,Experience_Years,Certifications,Salary,Satisfaction_Score,Age,Performance_Rating,Employment_Type
0,Engineering,11.0,1,60671.81,9.49,32.0,2.0,Part-time
1,Engineering,4.0,1,45659.33,3.97,NaN,3.1,Part-time
2,Marketing,NaN,3,28771.96,9.54,24.0,2.4,NaN
3,Marketing,3.0,1,NaN,1.35,38.0,3.1,Contract
4,Engineering,5.0,3,18813.08,4.84,49.0,1.5,Full-time
...,...,...,...,...,...,...,...,...
245,HR,5.0,0,46661.88,8.26,45.0,4.3,Contract
246,Marketing,11.0,3,62366.23,2.98,55.0,2.3,Intern
247,HR,20.0,2,NaN,8.40,46.0,1.1,NaN
248,Marketing,7.0,1,61220.52,7.73,50.0,1.6,Contract
249,Marketing,3.0,0,72514.57,2.30,52.0,1.9,Contract

In [8]:
df.drop([0, 1])   #drop the rows with the index 0 and 1

,Gender,Department,Experience_Years,Certifications,Salary,Satisfaction_Score,Age,Performance_Rating,Employment_Type
2,Male,Marketing,NaN,3,28771.96,9.54,24.0,2.4,NaN
3,Male,Marketing,3.0,1,NaN,1.35,38.0,3.1,Contract
4,Male,Engineering,5.0,3,18813.08,4.84,49.0,1.5,Full-time
5,Male,Marketing,12.0,3,NaN,2.70,50.0,1.5,Contract
6,Male,HR,19.0,4,40743.64,5.40,42.0,1.6,NaN
...,...,...,...,...,...,...,...,...,...
245,Male,HR,5.0,0,46661.88,8.26,45.0,4.3,Contract
246,Male,Marketing,11.0,3,62366.23,2.98,55.0,2.3,Intern
247,Male,HR,20.0,2,NaN,8.40,46.0,1.1,NaN
248,Female,Marketing,7.0,1,61220.52,7.73,50.0,1.6,Contract
249,Male,Marketing,3.0,0,72514.57,2.30,52.0,1.9,Contract

In [9]:
df.columns[0:3]  #displays 1st column name

Index(['Gender', 'Department', 'Experience_Years'], dtype='object')

In [10]:
df['Department']

0      Engineering
1      Engineering
2        Marketing
3        Marketing
4      Engineering
          ...
245             HR
246      Marketing
247             HR
248      Marketing
249      Marketing
Name: Department, Length: 250, dtype: object

In [11]:
df[['Department','Gender']]

      Department  Gender
0    Engineering    Male
1    Engineering    Male
2      Marketing    Male
3      Marketing    Male
4    Engineering    Male
..           ...     ...
245           HR    Male
246    Marketing    Male
247           HR    Male
248    Marketing  Female
249    Marketing    Male

[250 rows x 2 columns]

In [12]:
print (df['Salary'].isnull())

0      False
1      False
2      False
3       True
4      False
       ...
245    False
246    False
247     True
248    False
249    False
Name: Salary, Length: 250, dtype: bool

In [13]:
df.dropna() # drop rows with any NaNs

,Gender,Department,Experience_Years,Certifications,Salary,Satisfaction_Score,Age,Performance_Rating,Employment_Type
0,Male,Engineering,11.0,1,60671.81,9.49,32.0,2.0,Part-time
4,Male,Engineering,5.0,3,18813.08,4.84,49.0,1.5,Full-time
8,Male,Marketing,2.0,3,67832.02,8.42,58.0,3.9,Intern
10,Male,Engineering,19.0,5,52609.49,9.55,27.0,1.8,Intern
11,Male,Finance,15.0,0,63618.08,1.55,40.0,3.9,Part-time
...,...,...,...,...,...,...,...,...,...
243,Female,Marketing,15.0,5,35156.25,8.54,33.0,1.6,Full-time
245,Male,HR,5.0,0,46661.88,8.26,45.0,4.3,Contract
246,Male,Marketing,11.0,3,62366.23,2.98,55.0,2.3,Intern
248,Female,Marketing,7.0,1,61220.52,7.73,50.0,1.6,Contract
249,Male,Marketing,3.0,0,72514.57,2.30,52.0,1.9,Contract

In [14]:
df.dropna(axis=1) # drop columns with any NaNs

     Gender   Department  Certifications  Satisfaction_Score
0      Male  Engineering               1                9.49
1      Male  Engineering               1                3.97
2      Male    Marketing               3                9.54
3      Male    Marketing               1                1.35
4      Male  Engineering               3                4.84
..      ...          ...             ...                 ...
245    Male           HR               0                8.26
246    Male    Marketing               3                2.98
247    Male           HR               2                8.40
248  Female    Marketing               1                7.73
249    Male    Marketing               0                2.30

[250 rows x 4 columns]

In [15]:
df.fillna(0) # fill missing values with 0

,Gender,Department,Experience_Years,Certifications,Salary,Satisfaction_Score,Age,Performance_Rating,Employment_Type
0,Male,Engineering,11.0,1,60671.81,9.49,32.0,2.0,Part-time
1,Male,Engineering,4.0,1,45659.33,3.97,0.0,3.1,Part-time
2,Male,Marketing,0.0,3,28771.96,9.54,24.0,2.4,0
3,Male,Marketing,3.0,1,0.00,1.35,38.0,3.1,Contract
4,Male,Engineering,5.0,3,18813.08,4.84,49.0,1.5,Full-time
...,...,...,...,...,...,...,...,...,...
245,Male,HR,5.0,0,46661.88,8.26,45.0,4.3,Contract
246,Male,Marketing,11.0,3,62366.23,2.98,55.0,2.3,Intern
247,Male,HR,20.0,2,0.00,8.40,46.0,1.1,0
248,Female,Marketing,7.0,1,61220.52,7.73,50.0,1.6,Contract
249,Male,Marketing,3.0,0,72514.57,2.30,52.0,1.9,Contract

In [16]:
pd.set_option('display.max_rows', None) #Ensure Pandas doesn't truncate rows in the output screen
print(df['Employment_Type'].fillna(method='bfill')) # backward fill - copying the next valid value down the column

0      Part-time
1      Part-time
2       Contract
3       Contract
4      Full-time
5       Contract
6         Intern
7         Intern
8         Intern
9      Part-time
10        Intern
11     Part-time
12        Intern
13      Contract
14     Full-time
15      Contract
16      Contract
17      Contract
18     Part-time
19     Part-time
20     Part-time
21     Part-time
22     Part-time
23      Contract
24     Full-time
25        Intern
26     Part-time
27        Intern
28        Intern
29     Part-time
30        Intern
31     Full-time
32      Contract
33      Contract
34     Full-time
35        Intern
36     Part-time
37        Intern
38     Full-time
39        Intern
40      Contract
41        Intern
42     Full-time
43      Contract
44        Intern
45        Intern
46      Contract
47     Part-time
48      Contract
49     Part-time
50     Full-time
51     Full-time
52      Contract
53      Contract
54     Full-time
55     Part-time
56     Full-time
57      Contract
58     Full-time
59      Contract
60      Contract
61     Full-time
62     Part-time
63        Intern
64     Full-time
65        Intern
66     Full-time
67        Intern
68     Part-time
69     Part-time
70     Full-time
71      Contract
72        Intern
73      Contract
74      Contract
75      Contract
76     Part-time
77     Full-time
78     Full-time
79     Part-time
80     Part-time
81     Full-time
82      Contract
83        Intern
84        Intern
85        Intern
86      Contract
87     Full-time
88     Part-time
89     Full-time
90      Contract
91     Part-time
92      Contract
93        Intern
94        Intern
95      Contract
96     Part-time
97     Part-time
98     Full-time
99        Intern
100    Full-time
101    Full-time
102     Contract
103     Contract
104    Full-time
105       Intern
106     Contract
107    Full-time
108    Full-time
109    Full-time
110    Full-time
111    Full-time
112    Full-time
113     Contract
114       Intern
115    Full-time
116    Part-time
117     Contract
118     Contract
119    Full-time
120     Contract
121    Full-time
122       Intern
123       Intern
124     Contract
125     Contract
126    Part-time
127     Contract
128    Part-time
129       Intern
130       Intern
131    Full-time
132       Intern
133    Part-time
134     Contract
135    Full-time
136    Part-time
137     Contract
138    Full-time
139       Intern
140    Part-time
141     Contract
142    Full-time
143    Full-time
144       Intern
145     Contract
146       Intern
147       Intern
148     Contract
149     Contract
150     Contract
151    Part-time
152     Contract
153    Full-time
154       Intern
155    Part-time
156     Contract
157    Part-time
158     Contract
159    Part-time
160       Intern
161       Intern
162    Full-time
163    Full-time
164     Contract
165       Intern
166    Part-time
167    Part-time
168    Part-time
169    Full-time
170    Full-time
171    Full-time
172    Full-time
173     Contract
174    Part-time
175    Part-time
176       Intern
177     Contract
178       Intern
179     Contract
180    Part-time
181    Full-time
182    Full-time
183    Full-time
184    Full-time
185    Full-time
186       Intern
187     Contract
188    Part-time
189       Intern
190     Contract
191    Full-time
192     Contract
193     Contract
194    Full-time
195    Full-time
196    Full-time
197    Part-time
198    Full-time
199    Part-time
200    Full-time
201    Part-time
202     Contract
203       Intern
204     Contract
205     Contract
206    Full-time
207    Part-time
208       Intern
209    Full-time
210    Full-time
211    Full-time
212     Contract
213    Part-time
214    Part-time
215       Intern
216    Part-time
217    Part-time
218    Full-time
219    Full-time
220     Contract
221    Full-time
222    Full-time
223    Full-time
224    Full-time
225     Contract
226    Full-time
227       Intern
228       Intern
229       Intern
230       Intern
231    Full-time
232       Intern
233    Full-time
234     Contract
235       Intern
236    Part-time
237       Intern
238       Intern
239       Intern
240       Intern
241    Part-time
242    Full-time
243    Full-time
244     Contract
245     Contract
246       Intern
247     Contract
248     Contract
249     Contract
Name: Employment_Type, dtype: object

/tmp/ipykernel_10868/1692826722.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df['Employment_Type'].fillna(method='bfill')) # backward fill - copying the next valid value down the column

In [17]:
pd.set_option('display.max_rows', None) #Ensure Pandas doesn't truncate rows in the output screen
print(df['Salary'].fillna(method='ffill') )# forward fill - copying the next valid value down the column

0      60671.81
1      45659.33
2      28771.96
3      28771.96
4      18813.08
5      18813.08
6      40743.64
7      31117.37
8      67832.02
9      49380.37
10     52609.49
11     63618.08
12     49868.14
13     56771.17
14     62237.77
15     58501.34
16     54289.70
17     76746.69
18     76746.69
19     48713.55
20     36354.61
21     36354.61
22     53237.91
23     75634.93
24     64812.40
25     61463.07
26     50194.27
27     36864.52
28     47030.56
29     47030.56
30     24056.30
31     68625.71
32     81005.66
33     20825.91
34     20825.91
35     53444.94
36     53444.94
37     53913.60
38     53913.60
39     34642.72
40     69326.10
41     56967.75
42     41603.87
43     72575.38
44     42373.91
45     31372.39
46     52752.68
47     55297.36
48     57978.75
49     60445.27
50     57741.87
51     57132.40
52     41393.69
53     39788.84
54     61135.47
55     53651.85
56     53651.85
57     24390.84
58     42488.20
59     78605.28
60     58288.00
61     54433.26
62     60618.87
63     83126.76
64     79970.74
65     26307.19
66     26307.19
67     25798.84
68     38793.38
69     50823.79
70     50823.79
71     27042.82
72     21989.72
73     38528.13
74     63742.57
75     63742.57
76     75587.37
77     49515.05
78     62422.30
79     65148.42
80     42547.11
81     55817.67
82     59880.58
83     36362.64
84     74631.44
85     49417.82
86     51305.53
87     35789.88
88     38308.61
89     17052.28
90     50827.34
91     87585.34
92     34720.71
93     94642.95
94     71213.77
95     42896.17
96     50408.97
97     47973.50
98     75592.46
99     75592.46
100    67729.61
101    55372.58
102    48320.41
103    54896.35
104    43895.84
105    28216.94
106    62205.33
107    27482.53
108    27482.53
109    43402.04
110    59650.31
111    73470.57
112    68074.56
113    60086.38
114    40551.93
115    47247.96
116    45060.89
117    42945.78
118    43963.23
119    43562.93
120    43562.93
121    43562.93
122    43562.93
123    39057.89
124    26248.90
125    71232.24
126    38052.46
127    59911.63
128    57129.78
129    69782.58
130    46849.75
131    46849.75
132    26663.75
133     8230.47
134    52420.30
135    61632.09
136    57075.32
137    27053.54
138    65582.39
139    39526.76
140    36396.45
141    39190.52
142    51176.13
143    27729.48
144    49444.46
145    56441.72
146    56441.72
147    52639.35
148    29905.57
149    52233.35
150    34096.13
151    33230.82
152    29559.45
153    21331.19
154    41492.55
155    66933.33
156    83847.26
157    41396.22
158    66291.58
159    44081.27
160    25238.96
161    60514.13
162    60514.13
163    77270.29
164    26979.82
165    91940.49
166    73875.76
167    49731.15
168    45520.43
169    39262.85
170    39262.85
171    47240.96
172    57706.93
173    45584.50
174    71224.46
175    51875.69
176    46147.74
177    65364.30
178    25662.15
179    55114.83
180    50383.57
181    28837.24
182    24372.45
183    65155.18
184    64441.86
185    52588.38
186    75749.87
187    56614.52
188    68747.08
189    56304.87
190    45862.86
191    34137.03
192    40948.46
193    46143.17
194    70447.30
195    61548.79
196    54954.79
197    63050.15
198    57910.76
199    53929.06
200    27520.11
201    67087.36
202    43122.32
203    66328.10
204    67778.15
205    39949.41
206    64245.74
207    44585.19
208    44674.52
209    53862.10
210    54267.09
211    50578.27
212    29985.68
213    48178.30
214    84177.18
215     8239.94
216    63046.11
217    65856.87
218    29624.78
219    42958.42
220    34989.24
221    77809.48
222    66545.38
223    67271.38
224    51809.71
225    69681.38
226    49876.45
227    70387.36
228    47769.55
229    39811.37
230    77164.25
231    49687.27
232    36518.00
233    36355.49
234    36355.49
235    62666.64
236    62666.64
237    84469.38
238    67792.67
239    53857.07
240    71058.46
241    71058.46
242    22178.21
243    35156.25
244    35156.25
245    46661.88
246    62366.23
247    62366.23
248    61220.52
249    72514.57
Name: Salary, dtype: float64

/tmp/ipykernel_10868/1946290593.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df['Salary'].fillna(method='ffill') )# forward fill - copying the next valid value down the column

In [18]:
print(df.interpolate())  # fills missing (NaN) values in numeric columns by interpolating between existing values.

     Gender   Department  Experience_Years  Certifications     Salary  \
0      Male  Engineering              11.0               1  60671.810
1      Male  Engineering               4.0               1  45659.330
2      Male    Marketing               3.5               3  28771.960
3      Male    Marketing               3.0               1  23792.520
4      Male  Engineering               5.0               3  18813.080
5      Male    Marketing              12.0               3  29778.360
6      Male           HR              19.0               4  40743.640
7    Female           HR              14.0               0  31117.370
8      Male    Marketing               2.0               3  67832.020
9      Male    Marketing               7.0               2  49380.370
10     Male  Engineering              19.0               5  52609.490
11     Male      Finance              15.0               0  63618.080
12     Male    Marketing              12.0               0  49868.140
13     Male           HR              17.0               0  56771.170
14   Female  Engineering               9.0               4  62237.770
15     Male    Marketing              18.0               3  58501.340
16   Female           HR              16.0               4  54289.700
17   Female           HR              18.0               3  76746.690
18   Female      Finance               4.0               4  62730.120
19   Female  Engineering              20.0               4  48713.550
20     Male  Engineering               8.0               5  36354.610
21     Male      Finance              11.0               2  44796.260
22   Female      Finance              20.0               4  53237.910
23   Female  Engineering               0.0               5  75634.930
24     Male  Engineering               0.0               1  64812.400
25     Male    Marketing              14.0               2  61463.070
26     Male    Marketing               1.0               4  50194.270
27     Male      Finance              15.0               0  36864.520
28     Male    Marketing               7.0               1  47030.560
29     Male           HR              12.0               1  35543.430
30   Female    Marketing              20.0               5  24056.300
31     Male    Marketing               0.0               1  68625.710
32   Female           HR              15.0               2  81005.660
33   Female      Finance               6.0               4  20825.910
34     Male           HR               4.0               4  37135.425
35   Female    Marketing               2.0               0  53444.940
36     Male      Finance              11.0               5  53679.270
37     Male    Marketing              15.0               0  53913.600
38     Male           HR              18.0               1  44278.160
39     Male           HR               4.0               0  34642.720
40     Male    Marketing              13.0               2  69326.100
41     Male  Engineering               4.0               4  56967.750
42     Male  Engineering              14.0               1  41603.870
43     Male           HR              16.0               0  72575.380
44     Male           HR              13.0               5  42373.910
45     Male  Engineering              19.0               2  31372.390
46   Female  Engineering               4.0               2  52752.680
47     Male    Marketing              11.0               0  55297.360
48   Female    Marketing              15.0               4  57978.750
49   Female  Engineering              15.0               0  60445.270
50   Female    Marketing              20.0               1  57741.870
51     Male    Marketing               6.0               0  57132.400
52   Female      Finance               3.0               2  41393.690
53     Male    Marketing               0.0               0  39788.840
54   Female           HR               4.0               4  61135.470
55     Male    Marketing               9.0               5  53651.850
56     Male    Marketing               4.0               3  39021.345
57     Male  Engineering               3.0               0  24390.840
58     Male           HR               1.0               4  42488.200
59     Male    Marketing              19.0               4  78605.280
60   Female    Marketing               9.0               5  58288.000
61     Male      Finance              18.0               2  54433.260
62   Female    Marketing               0.0               4  60618.870
63   Female    Marketing               4.0               4  83126.760
64   Female      Finance              12.0               4  79970.740
65   Female  Engineering               3.0               4  26307.190
66   Female    Marketing              15.0               1  26053.015
67   Female      Finance              15.0               1  25798.840
68   Female           HR               1.0               2  38793.380
69     Male  Engineering              16.0               0  50823.790
70     Male           HR              19.0               4  38933.305
71   Female           HR              11.0               5  27042.820
72   Female      Finance              17.0               0  21989.720
73   Female    Marketing               2.0               5  38528.130
74   Female      Finance               0.0               0  63742.570
75   Female      Finance               0.0               2  69664.970
76   Female      Finance              18.0               4  75587.370
77     Male      Finance              10.0               4  49515.050
78     Male  Engineering               4.0               3  62422.300
79   Female    Marketing              11.0               5  65148.420
80     Male           HR               2.0               0  42547.110
81     Male           HR               0.0               0  55817.670
82   Female    Marketing               0.0               1  59880.580
83     Male           HR               7.0               3  36362.640
84     Male    Marketing               9.0               1  74631.440
85   Female           HR              10.0               1  49417.820
86     Male      Finance              11.0               1  51305.530
87     Male           HR              12.0               5  35789.880
88   Female    Marketing              11.0               5  38308.610
89     Male    Marketing              13.0               2  17052.280
90     Male    Marketing               1.0               2  50827.340
91     Male    Marketing              18.0               1  87585.340
92     Male    Marketing              17.0               3  34720.710
93     Male  Engineering               2.0               0  94642.950
94     Male  Engineering              16.0               5  71213.770
95     Male           HR               7.0               3  42896.170
96     Male    Marketing               9.0               4  50408.970
97     Male           HR               1.0               5  47973.500
98     Male    Marketing              18.0               5  75592.460
99     Male    Marketing               8.0               2  71661.035
100    Male  Engineering               6.0               0  67729.610
101    Male  Engineering               3.0               0  55372.580
102    Male      Finance              20.0               4  48320.410
103    Male  Engineering              17.0               4  54896.350
104    Male      Finance              12.0               5  43895.840
105    Male      Finance              10.0               1  28216.940
106    Male      Finance               3.0               2  62205.330
107    Male      Finance              20.0               2  27482.530
108    Male      Finance               3.0               5  35442.285
109  Female           HR               9.0               3  43402.040
110    Male  Engineering               4.0               1  59650.310
111  Female      Finance               8.0               5  73470.570
112    Male    Marketing               2.0               1  68074.560
113    Male  Engineering              16.0               1  60086.380
114    Male  Engineering               2.0               1  40551.930
115  Female      Finance              15.0               5  47247.960
116    Male           HR               3.0               2  45060.890
117    Male      Finance              17.0               2  42945.780
118    Male           HR              16.0               1  43963.230
119  Female    Marketing               6.0               3  43562.930
120    Male  Engineering               4.0               0  42436.670
121    Male    Marketing              11.0               5  41310.410
122  Female           HR              16.0               0  40184.150
123    Male           HR              12.0               3  39057.890
124    Male    Marketing               2.0               5  26248.900
125    Male           HR               8.0               1  71232.240
126    Male    Marketing              16.0               2  38052.460
127    Male  Engineering              16.0               0  59911.630
128    Male    Marketing              19.0               4  57129.780
129  Female  Engineering              15.0               4  69782.580
130    Male    Marketing              12.0               3  46849.750
131    Male           HR              18.0               1  36756.750
132    Male    Marketing              16.0               0  26663.750
133  Female           HR               3.0               1   8230.470
134    Male    Marketing              11.0               0  52420.300
135    Male    Marketing               8.0               3  61632.090
136  Female      Finance              18.0               3  57075.320
137    Male           HR              11.0               4  27053.540
138    Male      Finance               8.0               1  65582.390
139    Male           HR               6.0               5  39526.760
140    Male      Finance              13.0               4  36396.450
141    Male  Engineering              19.0               1  39190.520
142  Female    Marketing              18.0               4  51176.130
143  Female           HR              14.0               5  27729.480
144    Male           HR              15.0               2  49444.460
145    Male    Marketing              20.0               2  56441.720
146    Male           HR               4.0               2  54540.535
147    Male           HR               2.0               2  52639.350
148    Male      Finance              11.0               0  29905.570
149    Male           HR              19.0               2  52233.350
150  Female  Engineering              20.0               5  34096.130
151    Male  Engineering               3.0               3  33230.820
152    Male    Marketing              20.0               3  29559.450
153    Male           HR              15.0               0  21331.190
154    Male    Marketing               6.0               2  41492.550
155    Male  Engineering              12.0               2  66933.330
156    Male           HR              20.0               2  83847.260
157    Male           HR               9.0               4  41396.220
158    Male    Marketing               6.0               1  66291.580
159    Male  Engineering              13.0               4  44081.270
160    Male           HR               4.0               1  25238.960
161  Female    Marketing               2.0               2  60514.130
162  Female  Engineering              10.0               2  68892.210
163  Female    Marketing              10.0               4  77270.290
164  Female      Finance              17.0               4  26979.820
165    Male           HR              14.0               1  91940.490
166  Female      Finance              11.0               3  73875.760
167    Male  Engineering               8.0               1  49731.150
168    Male      Finance               9.0               4  45520.430
169  Female      Finance              11.0               5  39262.850
170  Female  Engineering              16.0               4  43251.905
171  Female    Marketing               5.0               5  47240.960
172  Female      Finance               6.0               0  57706.930
173  Female    Marketing              13.0               4  45584.500
174  Female      Finance              12.0               0  71224.460
175    Male    Marketing               7.0               3  51875.690
176  Female  Engineering               9.0               1  46147.740
177  Female      Finance               8.0               5  65364.300
178    Male  Engineering              17.0               1  25662.150
179    Male      Finance               1.0               0  55114.830
180    Male  Engineering               4.0               5  50383.570
181  Female  Engineering               4.0               1  28837.240
182  Female      Finance               5.0               4  24372.450
183    Male      Finance              18.0               2  65155.180
184    Male      Finance               7.0               0  64441.860
185    Male           HR              15.0               1  52588.380
186  Female    Marketing              12.0               0  75749.870
187  Female           HR               0.0               0  56614.520
188  Female           HR              19.0               5  68747.080
189  Female  Engineering              16.0               5  56304.870
190    Male      Finance               6.0               2  45862.860
191  Female    Marketing              12.0               4  34137.030
192    Male  Engineering               3.0               0  40948.460
193    Male           HR               3.0               1  46143.170
194  Female      Finance               5.0               3  70447.300
195  Female  Engineering              18.0               0  61548.790
196  Female      Finance              11.0               0  54954.790
197  Female  Engineering               6.0               2  63050.150
198  Female      Finance               9.0               4  57910.760
199    Male           HR              18.0               3  53929.060
200    Male    Marketing               6.0               5  27520.110
201  Female           HR               2.0               5  67087.360
202    Male    Marketing              12.0               1  43122.320
203  Female      Finance              12.0               3  66328.100
204  Female  Engineering              17.0               5  67778.150
205  Female           HR              19.0               1  39949.410
206  Female    Marketing               7.0               4  64245.740
207  Female           HR               8.0               1  44585.190
208    Male    Marketing               6.0               5  44674.520
209    Male           HR               0.0               2  53862.100
210    Male    Marketing               2.0               2  54267.090
211    Male    Marketing              12.0               2  50578.270
212  Female      Finance              16.0               5  29985.680
213    Male    Marketing               0.0               2  48178.300
214  Female      Finance               5.0               3  84177.180
215  Female    Marketing              20.0               4   8239.940
216  Female  Engineering               5.0               1  63046.110
217  Female  Engineering              11.0               1  65856.870
218    Male  Engineering              12.0               5  29624.780
219    Male    Marketing              12.0               2  42958.420
220    Male      Finance              14.0               2  34989.240
221  Female      Finance              20.0               0  77809.480
222  Female    Marketing              15.0               4  66545.380
223  Female  Engineering              20.0               3  67271.380
224    Male  Engineering              10.0               1  51809.710
225  Female      Finance               4.0               0  69681.380
226  Female  Engineering               3.0               0  49876.450
227  Female           HR               2.0               5  70387.360
228  Female      Finance              18.0               1  47769.550
229  Female  Engineering              19.0               5  39811.370
230  Female      Finance              17.0               3  77164.250
231    Male           HR              14.0               0  49687.270
232  Female      Finance               8.0               0  36518.000
233  Female      Finance              16.0               4  36355.490
234    Male      Finance              13.0               3  49511.065
235  Female      Finance              14.0               0  62666.640
236  Female           HR               0.0               3  73568.010
237  Female    Marketing              20.0               1  84469.380
238  Female      Finance               2.0               2  67792.670
239  Female      Finance              15.0               0  53857.070
240    Male  Engineering              10.0               4  71058.460
241    Male      Finance              11.0               1  46618.335
242  Female  Engineering               9.0               3  22178.210
243  Female    Marketing              15.0               5  35156.250
244    Male           HR               7.0               1  40909.065
245    Male           HR               5.0               0  46661.880
246    Male    Marketing              11.0               3  62366.230
247    Male           HR              20.0               2  61793.375
248  Female    Marketing               7.0               1  61220.520
249    Male    Marketing               3.0               0  72514.570

     Satisfaction_Score        Age  Performance_Rating Employment_Type
0                  9.49  32.000000            2.000000       Part-time
1                  3.97  28.000000            3.100000       Part-time
2                  9.54  24.000000            2.400000             NaN
3                  1.35  38.000000            3.100000        Contract
4                  4.84  49.000000            1.500000       Full-time
5                  2.70  50.000000            1.500000        Contract
6                  5.40  42.000000            1.600000             NaN
7                  1.62  50.000000            4.800000          Intern
8                  8.42  58.000000            3.900000          Intern
9                  8.46  41.000000            2.850000       Part-time
10                 9.55  27.000000            1.800000          Intern
11                 1.55  40.000000            3.900000       Part-time
12                 6.23  26.000000            1.600000          Intern
13                 4.74  24.000000            1.900000        Contract
14                 3.44  22.000000            4.900000       Full-time
15                 3.52  59.000000            2.000000             NaN
16                 4.13  36.000000            3.600000        Contract
17                 7.05  55.000000            4.900000        Contract
18                 5.98  56.000000            2.500000       Part-time
19                 4.60  46.000000            1.100000       Part-time
20                 0.76  45.000000            2.000000       Part-time
21                 0.78  33.000000            4.300000             NaN
22                 0.02  39.000000            4.500000       Part-time
23                 9.68  36.000000            3.000000        Contract
24                 0.05  37.000000            1.500000       Full-time
25                 1.03  48.000000            4.200000          Intern
26                 3.15  29.000000            4.700000       Part-time
27                 8.07  46.000000            3.400000          Intern
28                 9.62  38.000000            3.850000          Intern
29                 7.90  50.000000            4.300000       Part-time
30                 6.91  29.000000            3.700000          Intern
31                 5.21  38.500000            3.300000       Full-time
32                 0.87  48.000000            2.400000        Contract

/tmp/ipykernel_10868/942775018.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  print(df.interpolate())  # fills missing (NaN) values in numeric columns by interpolating between existing values.

In [19]:
df1 = pd.DataFrame({
    'brand': ['Maggi', 'Maggi', 'Yippee', 'Yippee', 'Top Ramen'],
    'style': ['pack', 'pack', 'cup', 'pack', 'pack'],
    'rating': [4.5, 4.5, 3.8, 14, 5]
})
df1

       brand style  rating
0      Maggi  pack     4.5
1      Maggi  pack     4.5
2     Yippee   cup     3.8
3     Yippee  pack    14.0
4  Top Ramen  pack     5.0

In [20]:
df1.drop_duplicates() # removes the duplicated rows

       brand style  rating
0      Maggi  pack     4.5
2     Yippee   cup     3.8
3     Yippee  pack    14.0
4  Top Ramen  pack     5.0

In [21]:
#To remove duplicates on specific column(s), use subset.
df1.drop_duplicates(subset=['brand'])

       brand style  rating
0      Maggi  pack     4.5
2     Yippee   cup     3.8
4  Top Ramen  pack     5.0

In [22]:
#To remove duplicates on specific column(s), use subset.
#to remove duplicates and keep last occurrences, use keep.
df1.drop_duplicates(subset=['brand', 'style'], keep='last')

       brand style  rating
1      Maggi  pack     4.5
2     Yippee   cup     3.8
3     Yippee  pack    14.0
4  Top Ramen  pack     5.0

In [23]:
#Categorical column missing values replaced with mode
#df.Employment_Type.mode()[0]
df.Employment_Type.fillna(df.Employment_Type.mode()[0])

0      Part-time
1      Part-time
2      Full-time
3       Contract
4      Full-time
5       Contract
6      Full-time
7         Intern
8         Intern
9      Part-time
10        Intern
11     Part-time
12        Intern
13      Contract
14     Full-time
15     Full-time
16      Contract
17      Contract
18     Part-time
19     Part-time
20     Part-time
21     Full-time
22     Part-time
23      Contract
24     Full-time
25        Intern
26     Part-time
27        Intern
28        Intern
29     Part-time
30        Intern
31     Full-time
32      Contract
33      Contract
34     Full-time
35        Intern
36     Part-time
37        Intern
38     Full-time
39        Intern
40      Contract
41        Intern
42     Full-time
43      Contract
44        Intern
45        Intern
46      Contract
47     Part-time
48      Contract
49     Part-time
50     Full-time
51     Full-time
52      Contract
53      Contract
54     Full-time
55     Part-time
56     Full-time
57      Contract
58     Full-time
59      Contract
60      Contract
61     Full-time
62     Part-time
63        Intern
64     Full-time
65        Intern
66     Full-time
67        Intern
68     Part-time
69     Part-time
70     Full-time
71      Contract
72        Intern
73      Contract
74      Contract
75      Contract
76     Part-time
77     Full-time
78     Full-time
79     Part-time
80     Part-time
81     Full-time
82      Contract
83        Intern
84        Intern
85        Intern
86      Contract
87     Full-time
88     Part-time
89     Full-time
90      Contract
91     Part-time
92      Contract
93        Intern
94        Intern
95      Contract
96     Part-time
97     Part-time
98     Full-time
99        Intern
100    Full-time
101    Full-time
102     Contract
103     Contract
104    Full-time
105       Intern
106     Contract
107    Full-time
108    Full-time
109    Full-time
110    Full-time
111    Full-time
112    Full-time
113     Contract
114       Intern
115    Full-time
116    Part-time
117     Contract
118     Contract
119    Full-time
120     Contract
121    Full-time
122       Intern
123       Intern
124     Contract
125     Contract
126    Part-time
127     Contract
128    Part-time
129       Intern
130       Intern
131    Full-time
132       Intern
133    Part-time
134     Contract
135    Full-time
136    Part-time
137     Contract
138    Full-time
139       Intern
140    Part-time
141     Contract
142    Full-time
143    Full-time
144       Intern
145     Contract
146       Intern
147       Intern
148     Contract
149     Contract
150     Contract
151    Part-time
152     Contract
153    Full-time
154       Intern
155    Part-time
156     Contract
157    Part-time
158     Contract
159    Part-time
160       Intern
161       Intern
162    Full-time
163    Full-time
164     Contract
165       Intern
166    Part-time
167    Part-time
168    Part-time
169    Full-time
170    Full-time
171    Full-time
172    Full-time
173     Contract
174    Part-time
175    Part-time
176       Intern
177     Contract
178       Intern
179     Contract
180    Part-time
181    Full-time
182    Full-time
183    Full-time
184    Full-time
185    Full-time
186       Intern
187     Contract
188    Part-time
189       Intern
190     Contract
191    Full-time
192     Contract
193     Contract
194    Full-time
195    Full-time
196    Full-time
197    Part-time
198    Full-time
199    Part-time
200    Full-time
201    Part-time
202     Contract
203       Intern
204     Contract
205     Contract
206    Full-time
207    Part-time
208       Intern
209    Full-time
210    Full-time
211    Full-time
212     Contract
213    Part-time
214    Part-time
215       Intern
216    Part-time
217    Part-time
218    Full-time
219    Full-time
220     Contract
221    Full-time
222    Full-time
223    Full-time
224    Full-time
225     Contract
226    Full-time
227       Intern
228       Intern
229       Intern
230       Intern
231    Full-time
232       Intern
233    Full-time
234     Contract
235       Intern
236    Part-time
237       Intern
238       Intern
239    Full-time
240       Intern
241    Part-time
242    Full-time
243    Full-time
244     Contract
245     Contract
246       Intern
247    Full-time
248     Contract
249     Contract
Name: Employment_Type, dtype: object

In [24]:
#numerical discrete values replaced with median.
df.Age.fillna(df.Age.median())

0      32.0
1      41.0
2      24.0
3      38.0
4      49.0
5      50.0
6      42.0
7      41.0
8      58.0
9      41.0
10     27.0
11     40.0
12     26.0
13     24.0
14     22.0
15     59.0
16     36.0
17     55.0
18     56.0
19     46.0
20     45.0
21     33.0
22     39.0
23     36.0
24     37.0
25     48.0
26     29.0
27     46.0
28     38.0
29     50.0
30     29.0
31     41.0
32     48.0
33     28.0
34     24.0
35     50.0
36     45.0
37     24.0
38     41.0
39     41.0
40     46.0
41     51.0
42     41.0
43     28.0
44     38.0
45     41.0
46     57.0
47     30.0
48     59.0
49     43.0
50     23.0
51     41.0
52     29.0
53     32.0
54     34.0
55     38.0
56     29.0
57     42.0
58     39.0
59     51.0
60     39.0
61     52.0
62     59.0
63     53.0
64     41.0
65     46.0
66     41.0
67     59.0
68     29.0
69     32.0
70     43.0
71     45.0
72     41.0
73     33.0
74     53.0
75     36.0
76     37.0
77     43.0
78     49.0
79     41.0
80     54.0
81     31.0
82     53.0
83     54.0
84     41.0
85     54.0
86     54.0
87     34.0
88     51.0
89     54.0
90     34.0
91     47.0
92     41.0
93     23.0
94     59.0
95     47.0
96     36.0
97     55.0
98     32.0
99     24.0
100    27.0
101    30.0
102    27.0
103    30.0
104    41.0
105    53.0
106    33.0
107    29.0
108    29.0
109    49.0
110    41.0
111    28.0
112    32.0
113    41.0
114    37.0
115    25.0
116    27.0
117    43.0
118    47.0
119    24.0
120    35.0
121    32.0
122    39.0
123    33.0
124    44.0
125    41.0
126    34.0
127    46.0
128    40.0
129    57.0
130    29.0
131    50.0
132    41.0
133    41.0
134    27.0
135    39.0
136    40.0
137    43.0
138    41.0
139    53.0
140    24.0
141    49.0
142    31.0
143    56.0
144    50.0
145    36.0
146    54.0
147    28.0
148    33.0
149    51.0
150    42.0
151    52.0
152    45.0
153    41.0
154    58.0
155    25.0
156    49.0
157    41.0
158    41.0
159    53.0
160    57.0
161    55.0
162    57.0
163    23.0
164    36.0
165    55.0
166    57.0
167    27.0
168    33.0
169    24.0
170    39.0
171    42.0
172    36.0
173    54.0
174    56.0
175    47.0
176    29.0
177    57.0
178    41.0
179    44.0
180    35.0
181    35.0
182    23.0
183    58.0
184    26.0
185    59.0
186    35.0
187    46.0
188    41.0
189    41.0
190    27.0
191    38.0
192    46.0
193    49.0
194    23.0
195    56.0
196    58.0
197    26.0
198    22.0
199    33.0
200    57.0
201    44.0
202    52.0
203    32.0
204    31.0
205    24.0
206    35.0
207    37.0
208    41.0
209    50.0
210    31.0
211    33.0
212    51.0
213    41.0
214    26.0
215    41.0
216    29.0
217    33.0
218    22.0
219    41.0
220    49.0
221    58.0
222    41.0
223    33.0
224    41.0
225    49.0
226    41.0
227    27.0
228    41.0
229    35.0
230    41.0
231    41.0
232    58.0
233    41.0
234    47.0
235    50.0
236    22.0
237    56.0
238    27.0
239    58.0
240    26.0
241    54.0
242    35.0
243    33.0
244    41.0
245    45.0
246    55.0
247    46.0
248    50.0
249    52.0
Name: Age, dtype: float64

In [25]:
# Numerical Continuous - replace missing values with mean
df['Salary'].fillna(df['Salary'].mean())

0      60671.810000
1      45659.330000
2      28771.960000
3      51449.357187
4      18813.080000
5      51449.357187
6      40743.640000
7      31117.370000
8      67832.020000
9      49380.370000
10     52609.490000
11     63618.080000
12     49868.140000
13     56771.170000
14     62237.770000
15     58501.340000
16     54289.700000
17     76746.690000
18     51449.357187
19     48713.550000
20     36354.610000
21     51449.357187
22     53237.910000
23     75634.930000
24     64812.400000
25     61463.070000
26     50194.270000
27     36864.520000
28     47030.560000
29     51449.357187
30     24056.300000
31     68625.710000
32     81005.660000
33     20825.910000
34     51449.357187
35     53444.940000
36     51449.357187
37     53913.600000
38     51449.357187
39     34642.720000
40     69326.100000
41     56967.750000
42     41603.870000
43     72575.380000
44     42373.910000
45     31372.390000
46     52752.680000
47     55297.360000
48     57978.750000
49     60445.270000
50     57741.870000
51     57132.400000
52     41393.690000
53     39788.840000
54     61135.470000
55     53651.850000
56     51449.357187
57     24390.840000
58     42488.200000
59     78605.280000
60     58288.000000
61     54433.260000
62     60618.870000
63     83126.760000
64     79970.740000
65     26307.190000
66     51449.357187
67     25798.840000
68     38793.380000
69     50823.790000
70     51449.357187
71     27042.820000
72     21989.720000
73     38528.130000
74     63742.570000
75     51449.357187
76     75587.370000
77     49515.050000
78     62422.300000
79     65148.420000
80     42547.110000
81     55817.670000
82     59880.580000
83     36362.640000
84     74631.440000
85     49417.820000
86     51305.530000
87     35789.880000
88     38308.610000
89     17052.280000
90     50827.340000
91     87585.340000
92     34720.710000
93     94642.950000
94     71213.770000
95     42896.170000
96     50408.970000
97     47973.500000
98     75592.460000
99     51449.357187
100    67729.610000
101    55372.580000
102    48320.410000
103    54896.350000
104    43895.840000
105    28216.940000
106    62205.330000
107    27482.530000
108    51449.357187
109    43402.040000
110    59650.310000
111    73470.570000
112    68074.560000
113    60086.380000
114    40551.930000
115    47247.960000
116    45060.890000
117    42945.780000
118    43963.230000
119    43562.930000
120    51449.357187
121    51449.357187
122    51449.357187
123    39057.890000
124    26248.900000
125    71232.240000
126    38052.460000
127    59911.630000
128    57129.780000
129    69782.580000
130    46849.750000
131    51449.357187
132    26663.750000
133     8230.470000
134    52420.300000
135    61632.090000
136    57075.320000
137    27053.540000
138    65582.390000
139    39526.760000
140    36396.450000
141    39190.520000
142    51176.130000
143    27729.480000
144    49444.460000
145    56441.720000
146    51449.357187
147    52639.350000
148    29905.570000
149    52233.350000
150    34096.130000
151    33230.820000
152    29559.450000
153    21331.190000
154    41492.550000
155    66933.330000
156    83847.260000
157    41396.220000
158    66291.580000
159    44081.270000
160    25238.960000
161    60514.130000
162    51449.357187
163    77270.290000
164    26979.820000
165    91940.490000
166    73875.760000
167    49731.150000
168    45520.430000
169    39262.850000
170    51449.357187
171    47240.960000
172    57706.930000
173    45584.500000
174    71224.460000
175    51875.690000
176    46147.740000
177    65364.300000
178    25662.150000
179    55114.830000
180    50383.570000
181    28837.240000
182    24372.450000
183    65155.180000
184    64441.860000
185    52588.380000
186    75749.870000
187    56614.520000
188    68747.080000
189    56304.870000
190    45862.860000
191    34137.030000
192    40948.460000
193    46143.170000
194    70447.300000
195    61548.790000
196    54954.790000
197    63050.150000
198    57910.760000
199    53929.060000
200    27520.110000
201    67087.360000
202    43122.320000
203    66328.100000
204    67778.150000
205    39949.410000
206    64245.740000
207    44585.190000
208    44674.520000
209    53862.100000
210    54267.090000
211    50578.270000
212    29985.680000
213    48178.300000
214    84177.180000
215     8239.940000
216    63046.110000
217    65856.870000
218    29624.780000
219    42958.420000
220    34989.240000
221    77809.480000
222    66545.380000
223    67271.380000
224    51809.710000
225    69681.380000
226    49876.450000
227    70387.360000
228    47769.550000
229    39811.370000
230    77164.250000
231    49687.270000
232    36518.000000
233    36355.490000
234    51449.357187
235    62666.640000
236    51449.357187
237    84469.380000
238    67792.670000
239    53857.070000
240    71058.460000
241    51449.357187
242    22178.210000
243    35156.250000
244    51449.357187
245    46661.880000
246    62366.230000
247    51449.357187
248    61220.520000
249    72514.570000
Name: Salary, dtype: float64

In [26]:
# 'inplace = True' -- it modifies the DataFrame directly and does not return a new object.
#df['Salary'].fillna(df['Salary'].mean(), inplace=True)